pay/protected/controllers/PaymentsController.php
<?php

class PaymentsController extends BaseController
{
    private $_model;
	/**
	 * Declares class-based actions.
	 */
	public function actions()
	{
		return array(
			// page action renders "static" pages stored under 'protected/views/site/pages'
			// They can be accessed via: index.php?r=site/page&view=FileName
			'page'=>array(
				'class'=>'CViewAction',
			),
		);
	}

    public function loadModel($id = 0)
    {
        if($this->_model===null)
        {
            if(!empty($id)){
                $condition = 'id = ' . $id;
            }
            $this->_model=Payments::model()->find(array(), $condition);

            if($this->_model===null)
                throw new CHttpException(404,'Запрашиваемая страница не существует.');
        }
        return $this->_model;
    }

	/**
	 * This is the default 'index' action that is invoked
	 * when an action is not explicitly requested by users.
	 */
	public function actionIndex($id=0)
	{
        $criteria = new CDbCriteria();

        $cid = Pers::model()->getUserCompany();

        if(!empty($id)){
            $criteria->condition = 't.pers_id ='.$id;
        }else{
            if(!empty($cid)){
                $criteria->select = 't.*';
                $criteria->join = 'LEFT JOIN pers pers ON t.pers_id = pers.id ';
                $criteria->join .= 'LEFT JOIN accounts acc ON pers.cid = acc.cid ';

                $criteria->condition = 'acc.cid ='. $cid;
                $criteria->order = 't.date ASC';
            }

        }

        $pages = new CPagination(Payments::model()->count());
        $pages->pageSize = 10;
        $pages->applyLimit($criteria);

        $dataProvider=new CActiveDataProvider('Payments', array(
            'criteria'=>$criteria,
            'pagination'=>array(
                'pageSize'=> 10,
            ),

        ));

        $this->render('payments', array('dataProvider'=>$dataProvider, 'pages' => $pages));
	}

    public function actionDelete($id)
    {
        $model = $this->loadModel($id);
        if($model===null)
            throw new CHttpException(404,'Запрашиваемая страница не существует.');

        $model->delete();
        $this->actionIndex();
        Yii::app()->end();

    }

    public function actionUpdate($id = 0)
    {
        if(!empty($id)){
            $model = $this->loadModel($id);
        }else{
            $model = new Payments();
        }

        if (isset($_POST['Payments'])) {
            $model->attributes = $_POST['Payments'];

            $model->date = date ('Y-m-d', strtotime($model->date));

            $date = strtotime("+1 month", strtotime($_POST['Payments']['date']));
            $date = strtotime("-1 day", $date);
            $model->payed_till = date("Y-m-d", $date);
            if ($model->validate()) {
                if ($model->save()) {
                    $this->actionIndex();
                    Yii::app()->end();
                }
            }

        }

        $model->date = date ('d-m-Y', strtotime($model->date));

        $pers = Pers::model()->findAll(array('order' => 'name'));

        $persList = CHtml::listData($pers, 'id','name');


        $this->render('payments_update', array('model' => $model, 'pers' => $persList));
    }

	/**
	 * This is the action to handle external exceptions.
	 */
	public function actionError()
	{
		if($error=Yii::app()->errorHandler->error)
		{
			if(Yii::app()->request->isAjaxRequest)
				echo $error['message'];
			else
				$this->render('error', $error);
		}
	}

    public function getUserName($id){
        $pers = Pers::model()->findByPk($id);
        return $pers->name;
    }
}

pay/protected/controllers/SiteController.php
<?php

class SiteController extends BaseController
{
    private $_model;
    /**
     * Declares class-based actions.
     */
    public function actions()
    {
        return array(
            // page action renders "static" pages stored under 'protected/views/site/pages'
            // They can be accessed via: index.php?r=site/page&view=FileName
            'page' => array(
                'class' => 'CViewAction',
            ),
        );
    }

    public function loadModel($id = 0)
    {
        if ($this->_model === null) {
            if (!empty($id)) {
                $condition = 'AND id = ' . $id;

                $this->_model = Pers::model()->find(array(
                    'condition' => 'del=:del '. $condition,
                    'params' => array(':del' => 0)
                ));
            } else {
                $this->_model = new Pers;
            }


            if ($this->_model === null)
                throw new CHttpException(404, 'Запрашиваемая страница не существует.');
        }
        return $this->_model;
    }

    /**
     * This is the default 'index' action that is invoked
     * when an action is not explicitly requested by users.
     */
    public function actionIndex()
    {
        if(Yii::app()->user->isGuest){
            $this->redirect(Yii::app()->createUrl('site/login'));
        }

        $criteria = new CDbCriteria();
        $criteria->condition = 'del=0 AND cid = '. $this->getUserCompany();
        $criteria->order = 'id ASC';

        $pages = new CPagination(Pers::model()->count());
        $pages->pageSize = 10;
        $pages->applyLimit($criteria);

        $dataProvider = new CActiveDataProvider('Pers', array(
            'criteria' => $criteria,
            'pagination' => array(
                'pageSize' => 50,
            ),

        ));

        $this->render('pers', array('dataProvider' => $dataProvider, 'pages' => $pages));
    }

    public function actionDelete($id)
    {
        $model = $this->loadModel($id);
        if ($model === null)
            throw new CHttpException(404, 'Запрашиваемая страница не существует.');

        $model->delete();
        $this->actionIndex();
        Yii::app()->end();

    }

    public function actionUpdate($id = 0)
    {
        if(!empty($id)){
            $model = $this->loadModel($id);
        }else{
            $model = new Pers();
        }

        if (isset($_POST['Pers'])) {
            $model->attributes = $_POST['Pers'];

            $model->cid = $this->getUserCompany();
            $model->date = date ('Y-m-d', strtotime($model->date));

            $model->date_end = date ('Y-m-d', strtotime($model->date_end));



            if ($model->validate()) {
                if ($model->save()) {
                    CVarDumper::dump($model->getErrors(), 5678, true);
                    $this->actionIndex();
                    Yii::app()->end();
                }
            }
        }

        $model->date = date ('d-m-Y', strtotime($model->date));
        $model->date_end = date ('d-m-Y', strtotime($model->date_end));

        $company = Companies::model()->findAll(array('order' => 'company_name'));
        $companyList = CHtml::listData($company, 'id','company_name');

        $countries = Countries::model()->findAll(array('order' => 'name'));
        $countriesList = CHtml::listData($countries, 'id','name');

        $docs = Docs::model()->findAll(array('order' => 'name'));
        $docsList = CHtml::listData($docs, 'code','name');

        $region = Region::model()->findAll(array('order' => 'name'));
        $regionList = CHtml::listData($region, 'id','name');

        $ifns = Ifns::model()->findAll(array('order' => 'name'));
        $ifnsList = CHtml::listData($ifns, 'code','name');

        $this->render('pers_update', array('model' => $model, 'company' => $companyList, 'countries' => $countriesList, 'docs' => $docsList, 'region' => $regionList, 'ifns' => $ifnsList));
    }

    public function getCompanyName($id){
        $comapny = Companies::model()->findByPk($id);
        return $comapny->company_name;
        //$comapny->company_name;
    }

    /**
     * This is the action to handle external exceptions.
     */
    public function actionError()
    {
        if ($error = Yii::app()->errorHandler->error) {
            if (Yii::app()->request->isAjaxRequest)
                echo $error['message'];
            else
                $this->render('error', $error);
        }
    }

    /**
     * Displays the login page
     */
    public function actionLogin()
    {
        $form = new Accounts();

        // Проверяем является ли пользователь гостем
        // ведь если он уже зарегистрирован - формы он не должен увидеть.
        if (!Yii::app()->user->isGuest) {
            throw new CException('Вы уже авторизованы!');
        } else {
            if (!empty($_POST['Accounts'])) {
                $form->attributes = $_POST['Accounts'];
                // Проверяем правильность данных
                if($form->validate('login')) {
                    $identity = new UserIdentity($form->login, $form->password);
                    $identity->authenticate();
                    Yii::app()->user->login($identity);

                    // если всё ок - кидаем на главную страницу
                    $this->redirect(Yii::app()->homeUrl);
                }
            }
            $this->render('login', array('model' => $form));
        }
    }

    /**
     * Logs out the current user and redirect to homepage.
     */
    public function actionLogout()
    {
        Yii::app()->user->logout();
        $this->redirect(Yii::app()->homeUrl);
    }

    public function getUserCompany(){
        $c = Accounts::model()->findByPk(Yii::app()->user->getId());
        return $c->cid;
    }

    public function getUserCompanyName(){
        $c = Accounts::model()->findByPk(Yii::app()->user->getId());
        $d = Companies::model()->findByPk($c->cid);
        return $d->company_name;
    }


    public function actionReport($print=0)
    {
        $criteria = new CDbCriteria();

        $criteria->order = 'date_end ASC';

        $cid = $this->getUserCompany();

        $criteria->condition = 'date_end >= DATE_SUB(CURDATE(), INTERVAL 5 DAY) AND date_end <= CURDATE() AND cid='.$cid;

        $pages = new CPagination(Pers::model()->count());
        $pages->pageSize = 10;
        $pages->applyLimit($criteria);

        $dataProvider=new CActiveDataProvider('Pers', array(
            'criteria'=>$criteria,
            'pagination'=>array(
                'pageSize'=> 50,
            ),
        ));

        $company = Companies::model()->findAll(array('order' => 'company_name'));
        $companyList = CHtml::listData($company, 'id','company_name');

        $countries = Countries::model()->findAll(array('order' => 'name'));
        $countriesList = CHtml::listData($countries, 'id','name');

        $docs = Docs::model()->findAll(array('order' => 'name'));
        $docsList = CHtml::listData($docs, 'code','name');

        $region = Region::model()->findAll(array('order' => 'name'));
        $regionList = CHtml::listData($region, 'id','name');

        $ifns = Ifns::model()->findAll(array('order' => 'name'));
        $ifnsList = CHtml::listData($ifns, 'code','name');

        if(!$print)
            $this->render('report', array('dataProvider'=>$dataProvider, 'pages' => $pages, 'company' => $companyList, 'countries' => $countriesList, 'docs' => $docsList, 'region' => $regionList, 'ifns' => $ifnsList));
        else
            $this->renderPartial('report', array('dataProvider'=>$dataProvider, 'pages' => $pages, 'company' => $companyList, 'countries' => $countriesList, 'docs' => $docsList, 'region' => $regionList, 'ifns' => $ifnsList));
    }

    public function actionOverdue($print=0)
    {
        $criteria = new CDbCriteria();

        $criteria->order = 'date_end ASC';

        $cid = $this->getUserCompany();
        $criteria->condition = 'date_end > CURDATE() AND cid='.$cid;

        $pages = new CPagination(Pers::model()->count());
        $pages->pageSize = 10;
        $pages->applyLimit($criteria);


        $dataProvider=new CActiveDataProvider('Pers', array(
            'criteria'=>$criteria,
            'pagination'=>array(
                'pageSize'=> 50,
            ),

        ));

        $company = Companies::model()->findAll(array('order' => 'company_name'));
        $companyList = CHtml::listData($company, 'id','company_name');

        $countries = Countries::model()->findAll(array('order' => 'name'));
        $countriesList = CHtml::listData($countries, 'id','name');

        $docs = Docs::model()->findAll(array('order' => 'name'));
        $docsList = CHtml::listData($docs, 'code','name');

        $region = Region::model()->findAll(array('order' => 'name'));
        $regionList = CHtml::listData($region, 'id','name');

        $ifns = Ifns::model()->findAll(array('order' => 'name'));
        $ifnsList = CHtml::listData($ifns, 'code','name');

        if(!$print)
            $this->render('override', array('dataProvider'=>$dataProvider, 'pages' => $pages, 'company' => $companyList, 'countries' => $countriesList, 'docs' => $docsList, 'region' => $regionList, 'ifns' => $ifnsList));
        else
            $this->renderPartial('override', array('dataProvider'=>$dataProvider, 'pages' => $pages, 'company' => $companyList, 'countries' => $countriesList, 'docs' => $docsList, 'region' => $regionList, 'ifns' => $ifnsList));

    }

    public function actionPrintReport(){
        $this->actionReport(1);
    }

    public function actionPrintOverride(){
        $this->actionOverdue(1);
    }
}

pay/protected/views/site/error.php
<?php
/* @var $this SiteController */
/* @var $error array */

$this->pageTitle=Yii::app()->name . ' - Error';
$this->breadcrumbs=array(
	'Error',
);
?>

<h2>Error <?php echo $code; ?></h2>

<div class="error">
<?php echo CHtml::encode($message); ?>
</div>

pay/protected/views/site/login.php
<?php
/* @var $this SiteController */
/* @var $model LoginForm */
/* @var $form CActiveForm  */

$this->pageTitle=Yii::app()->name . ' - Login';
$this->breadcrumbs=array(
	'Login',
);
?>

<h1>Login</h1>

<p>Please fill out the following form with your login credentials:</p>

<div class="form">
<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'login-form',
	'enableClientValidation'=>true,
	'clientOptions'=>array(
		'validateOnSubmit'=>true,
	),
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<div class="row">
		<?php echo $form->labelEx($model,'login'); ?>
		<?php echo $form->textField($model,'login'); ?>
		<?php echo $form->error($model,'login'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'password'); ?>
		<?php echo $form->passwordField($model,'password'); ?>
		<?php echo $form->error($model,'password'); ?>
		<p class="hint">
			Hint: You may login with <kbd>demo</kbd>/<kbd>demo</kbd> or <kbd>admin</kbd>/<kbd>admin</kbd>.
		</p>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Login'); ?>
	</div>

<?php $this->endWidget(); ?>
</div><!-- form -->

pay/protected/views/site/override.php
<?php
/* @var $this SiteController */

$this->pageTitle=Yii::app()->name;
?>
<div id="mainmenu">
		<?php $this->widget('zii.widgets.CMenu',array(
        'items'=>array(
            array('label'=>'Патенты со сроком менее 5 дней', 'url'=>array('/site/report')),
            array('label'=>'Просроченные патенты', 'url'=>array('/site/overdue')),
        ),
)); ?>
</div><!-- mainmenu -->
<br/>
<h2>Просроченные патенты</h2>
<?php
$widget = $this->widget('zii.widgets.grid.CGridView', array(
    'dataProvider' => $dataProvider,
    'enablePagination' => true,
    'columns' => array(
        'id',
        'name',
        array(
            'name' => 'type',
            'value' => '$data->getTypeName($data->type)',
        ),
        'doc_num',
        array(
            'name' => 'nationality',
            'value' => '$data->getNationalName($data->nationality)',
        ),
        'patent_num',
        array(
            'name' => 'date',
            'value' => 'date("d-m-Y", strtotime($data->date))',
        ),
        array(
            'name' => 'date_end',
            'value' => 'date("d-m-Y", strtotime($data->date_end))',
        ),
        array(
            'name' => 'Дата очередного продления',
            'value' => '$data->getPayDate($data->id)',
        ),
        'phone',
        /* array(
        'name'=>'Компания',
        'value'=>'$data->getCompanyName($data->cid)',
        ),*/
        'ifns',
//'region',
// 'address',
        'comment',
        array(
            'class' => 'CButtonColumn',
            'template' => '{payments} {update} {delete}',
            'buttons' => array
            (
                'payments' => array
                (
                    'label' => '[-]',
                    'options' => array(
                        'title' => 'Реестр платежей'
                    ),
                    'url' => 'Yii::app()->createUrl("payments/index", array("id"=>$data->id))',
//'click'=>'function(){alert("Going down!");}',
                ),
            ),
        ),
    ),
));
echo CHtml::button('Печать', array('onclick' => 'js:document.location.href="PrintOverride"'));
?>

pay/protected/views/site/pers.php
<?php
/* @var $this SiteController */

$this->pageTitle=Yii::app()->name;

echo CHtml::button('Добавить', array('onclick' => 'js:document.location.href="update"'));

$widget = $this->widget('zii.widgets.grid.CGridView', array(
    'dataProvider'=>$dataProvider,
    'enablePagination' => true,
    'columns'=>array(
        'id',
        'name',
        array(
            'name'=>'type',
            'value'=>'$data->getTypeName($data->type)',
        ),
        'doc_num',
        array(
            'name'=>'nationality',
            'value'=>'$data->getNationalName($data->nationality)',
        ),
        'patent_num',
        array(
            'name'=>'date',
            'value'=>'date("d-m-Y", strtotime($data->date))',
        ),
        array(
            'name'=>'date_end',
            'value'=>'date("d-m-Y", strtotime($data->date_end))',
        ),
        array(
            'name'=>'Дата очередного продления',
            'value'=>'$data->getPayDate($data->id)',
        ),
        'phone',
       /* array(
            'name'=>'Компания',
            'value'=>'$data->getCompanyName($data->cid)',
        ),*/
        'ifns',
        //'region',
       // 'address',
        'comment',
        array(
            'class' => 'CButtonColumn',
            'template' => '{payments} {update} {delete}',
            'buttons'=>array
                (
                    'payments' => array
                    (
                        'label'=>'[-]',
                        'options'=>array(
                            'title' => 'Реестр платежей'
                        ),
                        'url'=>'Yii::app()->createUrl("payments/index", array("id"=>$data->id))',
                        //'click'=>'function(){alert("Going down!");}',
                    ),
                ),
        ),
    ),
));
?>

pay/protected/views/site/pers_update.php
<?php
/**
 * Created by PhpStorm.
 * User: marduk
 * Date: 11.08.2015
 * Time: 16:26
 */
?>
<h2>Редактирование</h2>
<div class="form">
    <?php $form = $this->beginWidget('CActiveForm'); ?>

    <?php echo $form->errorSummary($model); ?>
    <?php if(!empty($model->id)){ ?>
        <div class="row">
            <?php echo $form->hiddenField($model, 'id') ?>
            <?php echo $form->error($model, 'id') ?>
        </div>
    <?php }?>

    <div class="row">
        <?php echo $form->label($model, 'name'); ?>
        <?php echo $form->textField($model, 'name'); ?>
        <?php echo $form->error($model,'name'); ?>
    </div>
    <div class="row">
        <?php echo $form->label($model, 'type'); ?>
        <?php echo $form->dropDownList($model, 'type', $docs);  ?>
        <?php echo $form->error($model,'type'); ?>
    </div>
    <div class="row">
        <?php echo $form->label($model, 'doc_num'); ?>
        <?php echo $form->textField($model, 'doc_num'); ?>
        <?php echo $form->error($model,'doc_num'); ?>
    </div>
    <div class="row">
        <?php echo $form->label($model, 'nationality'); ?>
        <?php echo $form->dropDownList($model, 'nationality', $countries);  ?>
        <?php echo $form->error($model,'nationality'); ?>
    </div>

    <div class="row">
        <?php echo $form->label($model, 'patent_num'); ?>
        <?php echo $form->textField($model, 'patent_num'); ?>
        <?php echo $form->error($model,'patent_num'); ?>
    </div>


    <div class="row">
        <?php echo $form->label($model, 'date'); ?>
        <?php
        $this->widget('zii.widgets.jui.CJuiDatePicker',array(
            'name'=>'Date',
            'language'=>'ru',
            'model'=>$model,
            'attribute'=>'date',

            // additional javascript options for the date picker plugin
            'options'=>array(
                'showAnim'=>'fold',
                'dateFormat'=>'dd-mm-yy',
                'showButtonPanel' => 'true'
            ),
            'htmlOptions'=>array(
                'style'=>'height:20px;'
            ),
        )); ?>
        <?php echo $form->error($model,'date'); ?>
    </div>
   <!-- <div class="row">
        <?php /*echo $form->label($model, 'date_end'); */?>
        <?php
/*        $this->widget('zii.widgets.jui.CJuiDatePicker',array(
            'name'=>'Date_end',
            'language'=>'ru',
            'model'=>$model,
            'attribute'=>'date_end',

            // additional javascript options for the date picker plugin
            'options'=>array(
                'showAnim'=>'fold',
                'dateFormat'=>'dd-mm-yy',
                'showButtonPanel' => 'true'
            ),
            'htmlOptions'=>array(
                'style'=>'height:20px;'
            ),
        )); */?>
        <?php /*echo $form->error($model,'date_end'); */?>
    </div>-->

    <div class="row">
        <?php echo $form->labelEx($model,'phone'); ?>
        <?php
        $this->widget('CMaskedTextField', array(
            'model' => $model,
            'attribute' => 'phone',
            'mask' => '+7-999-999-9999',
            'placeholder' => '*',
            'completed' => 'function(){console.log("ok");}',
        ));
        ?>
        <?php echo $form->error($model,'phone'); ?>
    </div>

    <div class="row">
        <?php //echo $form->dropDownList($model, 'cid', $company);  ?>
        <?php echo $form->hiddenField($model, 'cid'); ?>
        <?php echo $form->error($model,'cid'); ?>
    </div>
    <div class="row">
        <?php echo $form->label($model, 'region'); ?>
        <?php echo $form->dropDownList($model, 'region', $region);  ?>
        <?php echo $form->error($model,'region'); ?>
    </div>
    <div class="row">
        <?php echo $form->label($model, 'address'); ?>
        <?php echo $form->textField($model, 'address'); ?>
        <?php echo $form->error($model,'address'); ?>
    </div>
    <div class="row">
        <?php echo $form->label($model, 'ifns'); ?>
        <?php echo $form->dropDownList($model, 'ifns', $ifns);  ?>
        <?php echo $form->error($model,'ifns'); ?>
    </div>
    <div class="row">
        <?php echo $form->label($model, 'comment'); ?>
        <?php echo $form->textArea($model, 'comment'); ?>
        <?php echo $form->error($model,'comment'); ?>
    </div>



    <div class="row submit">
       <?php echo CHtml::submitButton("Сохранить"); ?>
    </div>
    <?php $this->endWidget(); ?></div>
<!-- form -->

pay/protected/views/site/report.php
<?php
/* @var $this SiteController */

$this->pageTitle = Yii::app()->name;
?>
    <div id="mainmenu">
        <?php $this->widget('zii.widgets.CMenu', array(
            'items' => array(
                array('label' => 'Патенты со сроком менее 5 дней', 'url' => array('/site/report')),
                array('label' => 'Просроченные патенты', 'url' => array('/site/overdue')),
            ),
        )); ?>
    </div><!-- mainmenu -->
    <br/>
    <h2>Патенты со сроком менее 5 дней</h2>
<?php
$widget = $this->widget('zii.widgets.grid.CGridView', array(
    'dataProvider' => $dataProvider,
    'enablePagination' => true,
    'columns' => array(
        'id',
        'name',
        array(
            'name' => 'type',
            'value' => '$data->getTypeName($data->type)',
        ),
        'doc_num',
        array(
            'name' => 'nationality',
            'value' => '$data->getNationalName($data->nationality)',
        ),
        'patent_num',
        array(
            'name' => 'date',
            'value' => 'date("d-m-Y", strtotime($data->date))',
        ),
        array(
            'name' => 'date_end',
            'value' => 'date("d-m-Y", strtotime($data->date_end))',
        ),
        array(
            'name' => 'Дата очередного продления',
            'value' => '$data->getPayDate($data->id)',
        ),
        'phone',
        /* array(
        'name'=>'Компания',
        'value'=>'$data->getCompanyName($data->cid)',
        ),*/
        'ifns',
//'region',
// 'address',
        'comment',
        array(
            'class' => 'CButtonColumn',
            'template' => '{payments} {update} {delete}',
            'buttons' => array
            (
                'payments' => array
                (
                    'label' => '[-]',
                    'options' => array(
                        'title' => 'Реестр платежей'
                    ),
                    'url' => 'Yii::app()->createUrl("payments/index", array("id"=>$data->id))',
//'click'=>'function(){alert("Going down!");}',
                ),
            ),
        ),
    ),
));
echo CHtml::button('Печать', array('onclick' => 'js:document.location.href="PrintReport"'));
?>